var argv = require('yargs')
    .usage('HTML Asset Generator (HAG)\nUsage: node generator <command> <args>')
    .default('p', 12020)
    .alias('p', 'port')
    .describe('p', 'Port number for local template server')
    .default('t', 'templates')
    .alias('t', 'templatesPath')
    .describe('t', 'Template directory')
    .default('o', 'build')
    .alias('o', 'outputPath')
    .describe('o', 'Output directory for assets')
    .default('i', 'instructions')
    .alias('i', 'instructionsPath')
    .describe('i', 'Instructions directory')
    .help('h', 'Help and Instructions')
    .alias('h', 'help')
    .epilogue('HAG is available on an ISC License, created by John Beech aka Markavian, 2015')
    .argv;

module.exports = argv;
